class CreateDbPekerjaans < ActiveRecord::Migration
  def change
    create_table :db_pekerjaans do |t|
      t.string :kd_kab
      t.string :nama_kab
      t.string :kd_kec
      t.string :nama_kec
      t.string :kd_kel
      t.string :desa_kel
      t.integer :laki
      t.integer :perempuan
      t.integer :belum_tidak_bekerja
      t.integer :mengurus_rumah_tangga
      t.integer :pelajar_mahasiswa
      t.integer :pensiunan
      t.integer :pegawai_negeri_sipil
      t.integer :tentara_nasional_indonesia
      t.integer :kepolisian_ri
      t.integer :perdagangan
      t.integer :petani_pekebun
      t.integer :peternak
      t.integer :nelayan_perikanan
      t.integer :industri
      t.integer :konstruksi
      t.integer :transportasi
      t.integer :karyawan_swasta
      t.integer :karyawan_bumn
      t.integer :karyawan_bumd
      t.integer :karyawan_honorer
      t.integer :buruh_harian_lepas
      t.integer :buruh_tani_perkebunan
      t.integer :buruh_nelayan_perikanan
      t.integer :buruh_peternakan
      t.integer :pembantu_rumah_tangga
      t.integer :tukang_cukur
      t.integer :tukang_lisrik
      t.integer :tukang_batu
      t.integer :tukang_kayu
      t.integer :tukang_sol_sepatu
      t.integer :tukang_las_pandai_besi
      t.integer :tukang_jahit
      t.integer :tukang_gigi
      t.integer :penata_rias
      t.integer :penata_busana
      t.integer :penata_rambut
      t.integer :mekanik
      t.integer :seniman
      t.integer :tabib
      t.integer :paraji
      t.integer :perancang_busana
      t.integer :penterjemah
      t.integer :imam_mesjid
      t.integer :pendeta
      t.integer :pastor
      t.integer :wartawan
      t.integer :ustadz_mubaligh
      t.integer :juru_masak
      t.integer :promotor_acara
      t.integer :anggota_dpr_ri
      t.integer :anggota_dpd
      t.integer :anggota_bpk
      t.integer :presiden
      t.integer :wakil_presiden
      t.integer :anggota_mahkamah_konstitusi
      t.integer :anggota_kabinet_kementrian
      t.integer :duta_besar
      t.integer :gubernur
      t.integer :wakil_gubernur
      t.integer :bupati
      t.integer :wakil_bupati
      t.integer :walikota
      t.integer :wakil_walikota
      t.integer :anggota_dprd_provinsi
      t.integer :anggota_dprd_kabupaten_kota
      t.integer :dosen
      t.integer :guru
      t.integer :pilot
      t.integer :pengacara
      t.integer :notaris
      t.integer :arsitek
      t.integer :akuntan
      t.integer :konsultan
      t.integer :dokter
      t.integer :bidan
      t.integer :perawat
      t.integer :apoteker
      t.integer :psikiater_psikolog
      t.integer :penyiar_televisi
      t.integer :penyiar_radio
      t.integer :pelaut
      t.integer :peneliti
      t.integer :sopir
      t.integer :pialang
      t.integer :paranormal
      t.integer :pedagang
      t.integer :perangkat_desa
      t.integer :kepala_desa
      t.integer :biarawati
      t.integer :wiraswasta
      t.integer :lainnya
      t.integer :jumlah_penduduk
      
      t.timestamps
    end
  end
end
