require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DbJmlhPddksController do

  # This should return the minimal set of attributes required to create a valid
  # DbJmlhPddk. As you add validations to DbJmlhPddk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "kdkec" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DbJmlhPddksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all db_jmlh_pddks as @db_jmlh_pddks" do
      db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
      get :index, {}, valid_session
      assigns(:db_jmlh_pddks).should eq([db_jmlh_pddk])
    end
  end

  describe "GET show" do
    it "assigns the requested db_jmlh_pddk as @db_jmlh_pddk" do
      db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
      get :show, {:id => db_jmlh_pddk.to_param}, valid_session
      assigns(:db_jmlh_pddk).should eq(db_jmlh_pddk)
    end
  end

  describe "GET new" do
    it "assigns a new db_jmlh_pddk as @db_jmlh_pddk" do
      get :new, {}, valid_session
      assigns(:db_jmlh_pddk).should be_a_new(DbJmlhPddk)
    end
  end

  describe "GET edit" do
    it "assigns the requested db_jmlh_pddk as @db_jmlh_pddk" do
      db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
      get :edit, {:id => db_jmlh_pddk.to_param}, valid_session
      assigns(:db_jmlh_pddk).should eq(db_jmlh_pddk)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DbJmlhPddk" do
        expect {
          post :create, {:db_jmlh_pddk => valid_attributes}, valid_session
        }.to change(DbJmlhPddk, :count).by(1)
      end

      it "assigns a newly created db_jmlh_pddk as @db_jmlh_pddk" do
        post :create, {:db_jmlh_pddk => valid_attributes}, valid_session
        assigns(:db_jmlh_pddk).should be_a(DbJmlhPddk)
        assigns(:db_jmlh_pddk).should be_persisted
      end

      it "redirects to the created db_jmlh_pddk" do
        post :create, {:db_jmlh_pddk => valid_attributes}, valid_session
        response.should redirect_to(DbJmlhPddk.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved db_jmlh_pddk as @db_jmlh_pddk" do
        # Trigger the behavior that occurs when invalid params are submitted
        DbJmlhPddk.any_instance.stub(:save).and_return(false)
        post :create, {:db_jmlh_pddk => { "kdkec" => "invalid value" }}, valid_session
        assigns(:db_jmlh_pddk).should be_a_new(DbJmlhPddk)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DbJmlhPddk.any_instance.stub(:save).and_return(false)
        post :create, {:db_jmlh_pddk => { "kdkec" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested db_jmlh_pddk" do
        db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
        # Assuming there are no other db_jmlh_pddks in the database, this
        # specifies that the DbJmlhPddk created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DbJmlhPddk.any_instance.should_receive(:update_attributes).with({ "kdkec" => "1" })
        put :update, {:id => db_jmlh_pddk.to_param, :db_jmlh_pddk => { "kdkec" => "1" }}, valid_session
      end

      it "assigns the requested db_jmlh_pddk as @db_jmlh_pddk" do
        db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
        put :update, {:id => db_jmlh_pddk.to_param, :db_jmlh_pddk => valid_attributes}, valid_session
        assigns(:db_jmlh_pddk).should eq(db_jmlh_pddk)
      end

      it "redirects to the db_jmlh_pddk" do
        db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
        put :update, {:id => db_jmlh_pddk.to_param, :db_jmlh_pddk => valid_attributes}, valid_session
        response.should redirect_to(db_jmlh_pddk)
      end
    end

    describe "with invalid params" do
      it "assigns the db_jmlh_pddk as @db_jmlh_pddk" do
        db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DbJmlhPddk.any_instance.stub(:save).and_return(false)
        put :update, {:id => db_jmlh_pddk.to_param, :db_jmlh_pddk => { "kdkec" => "invalid value" }}, valid_session
        assigns(:db_jmlh_pddk).should eq(db_jmlh_pddk)
      end

      it "re-renders the 'edit' template" do
        db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DbJmlhPddk.any_instance.stub(:save).and_return(false)
        put :update, {:id => db_jmlh_pddk.to_param, :db_jmlh_pddk => { "kdkec" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested db_jmlh_pddk" do
      db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
      expect {
        delete :destroy, {:id => db_jmlh_pddk.to_param}, valid_session
      }.to change(DbJmlhPddk, :count).by(-1)
    end

    it "redirects to the db_jmlh_pddks list" do
      db_jmlh_pddk = DbJmlhPddk.create! valid_attributes
      delete :destroy, {:id => db_jmlh_pddk.to_param}, valid_session
      response.should redirect_to(db_jmlh_pddks_url)
    end
  end

end
